// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLgQmG4h5zN2hQqUxfnJiFf8AUKr2ie7s',
    appId: '1:900757153916:web:2625347b764afc27bc41f9',
    messagingSenderId: '900757153916',
    projectId: 'brsk-test-2',
    authDomain: 'brsk-test-2.firebaseapp.com',
    storageBucket: 'brsk-test-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWGwkNyuS-zxQQO2u3iiP3qItkewAIdw',
    appId: '1:900757153916:android:854847c75b35c770bc41f9',
    messagingSenderId: '900757153916',
    projectId: 'brsk-test-2',
    storageBucket: 'brsk-test-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQ1LrpLv1HjYeyradmQCV0Q2Pfe3Lf8k',
    appId: '1:900757153916:ios:c5ba6121906007cbbc41f9',
    messagingSenderId: '900757153916',
    projectId: 'brsk-test-2',
    storageBucket: 'brsk-test-2.firebasestorage.app',
    iosBundleId: 'com.example.brskTest2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLgQmG4h5zN2hQqUxfnJiFf8AUKr2ie7s',
    appId: '1:900757153916:web:28e22e0f9b3c7e98bc41f9',
    messagingSenderId: '900757153916',
    projectId: 'brsk-test-2',
    authDomain: 'brsk-test-2.firebaseapp.com',
    storageBucket: 'brsk-test-2.firebasestorage.app',
  );
}